// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ItemFormController from "./item_form_controller"
application.register("item-form", ItemFormController)

import MapController from "./map_controller"
application.register("map", MapController)

import StoreShowController from "./store_show_controller"
application.register("store-show", StoreShowController)
